name: Build and deploy Python app to Azure Web App - financial-rag-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1A49C63B02A740208EDDAAED8F7E7E82 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_65F24F9F64C74205A59132F52A6AA654 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_983072FA23B546C587F7BCCCBE61C9DE }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'financial-rag-app'
          slot-name: 'Production'
          package: .
